### PR TITLE
Feature/raw disk

### PR DESCRIPTION
**Pull request by jsvisa**
@ijump @ddysher  Merge from upstream, and add `caiexec` exector; 

config file changed from 

```
  "glusterfs" : {

      "_executor_comment": "Execute plugin. Possible choices: mock, ssh",
      "executor" : "ssh",

      "_db_comment": "Database file name",
      "db" : "heketi.db",
      "sshexec": {
          "keyfile": "/root/.ssh/delweng.id_rsa",
          "user": "root",
          "port": "22"
      },

      "loglevel": "debug",

      "expand_method": "quota"
  }
```

to 

```
  "glusterfs" : {

      "_executor_comment": "Execute plugin. Possible choices: mock, ssh",
      "executor" : "cai",

      "_db_comment": "Database file name",
      "db" : "heketi.db",
      "caiexec": {
          "keyfile": "/root/.ssh/delweng.id_rsa",
          "user": "root",
          "port": "22"
      },

      "loglevel": "debug",

      "expand_method": "quota"
  }
```

### CODE REVIEW

**Comment by deyuanix** [comment]
@jsvisa This is hard to review.   You can create a new branch that's even with upstream master and create a PR to merge to that branch, diff will be clearer this way.

**Comment by jsvisa** [comment]
@ddysher PLEASE merge #3 first

**Comment by deyuanix** [comment]
@jsvisa rebase?

**Comment by jsvisa** [comment]
@ddysher 没道理啊，按理说  [caicloud/heketi: RESTful based volume management framework for GlusterFS](https://github.com/caicloud/heketi/tree/master) 已经更新了，前面的 commit 就应该看不到了，或者说我开个新的 PR

**Pull request closed without merging**
